[package]
name = "rustlings"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rustlings"
path = "src/game/main.rs"

[[bin]]
name = "rustlings-tools"
path = "src/tools/main.rs"

[dependencies]
anyhow = "1.0.101"
clap = "4.5.57"
sdl3 = { version = "0.17.3" }
